# Generated by Django 3.2 on 2021-08-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('own', models.CharField(max_length=20)),
                ('type', models.IntegerField()),
                ('create_time', models.CharField(max_length=50)),
                ('upload_time', models.CharField(max_length=50)),
                ('validity', models.DateTimeField()),
                ('limit_time', models.IntegerField()),
                ('count', models.IntegerField()),
                ('status', models.IntegerField()),
                ('hash', models.CharField(max_length=20)),
            ],
        ),
    ]
