# Generated by Django 3.2 on 2021-08-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
