# Generated by Django 3.2 on 2021-08-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_alter_questionnaire_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('upload_time', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='status',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='upload_time',
        ),
    ]
