# Generated by Django 3.2 on 2021-08-21 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_auto_20210821_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='count',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='description',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='limit_time',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='own',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='status',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='title',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='type',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='upload_time',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='validity',
        ),
    ]
