# Generated by Django 3.2 on 2021-08-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('qid', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('type', models.IntegerField()),
                ('title', models.TextField()),
                ('must', models.IntegerField()),
                ('choise', models.TextField()),
            ],
        ),
    ]
