# Generated by Django 3.1.1 on 2021-08-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20210822_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questionaire_id',
            new_name='questionnaire_id',
        ),
    ]
