# Generated by Django 3.1.1 on 2021-08-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20210822_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='username',
        ),
    ]
