# Global values

ERROR = 0
ACCEPT = 1
FORM_ERROR = r"参数格式错误，请检查传参"

SAVED = 0
RELEASE = 1
CLOSED = 2
DELETED = 3

SINGLE_CHOICE = 0
MULTIPLE_CHOICE = 1
COMPLETION = 2
DESCRIPTION = 3
GRADING = 4

SEPARATOR = "Y@7$"

NORMAL = 0
VOTING_BEFORE = 1
VOTING_AFTER = 2
VOTING_BOTH = 3
VOTING_NO = 4
SIGNUP = 5
TESTING_SCORE = 6
TESTING_CORRECTION = 7
TESTING_BOTH = 8
TESTING_NO = 9

NO_CERTIFICATION = 0
EMAIL_CERTIFICATION = 1
WEAK_CERTIFICATION = 2
STRONG_CERTIFICATION = 3