# Generated by Django 3.2 on 2021-08-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210821_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
